### ISSUE TITLE
Releases missing from Repo

### ISSUE THREAD

**Issue by darren-johnson** [hashicorp/terraform-provider-http#103]
Hi the Releases are missing from this repo meaning the latest version cannot be queried via the github api.

We use this functionality to dynamically ensure we are running the latest version of terraform. Could this be added please?

**Comment by bflad** [comment]
Hi @darren-johnson 👋  Thank you for raising this.

There are no plans to support GitHub Release assets for HashiCorp Terraform providers, beyond potentially updating our release process to also create a GitHub Release with the relevant CHANGELOG details. The binary files will not be hosted on GitHub. That work for this repository can be tracked at: https://github.com/hashicorp/terraform-provider-http/issues/92

The canonical sources for HashiCorp Terraform provider releases are [Terraform Registry](https://registry.terraform.io/) and [releases.hashicorp.com](https://releases.hashicorp.com/). For Terraform CLI, the [downloads page](https://www.terraform.io/downloads.html) is always up-to-date with the latest stable CLI release.

If you would like to automate finding the latest available versions from those two sources, one option is using the [Terraform Provider Registry Protocol](https://www.terraform.io/docs/internals/provider-registry-protocol.html), such as:

```shell
curl 'https://registry.terraform.io/v1/providers/hashicorp/http/versions'
```

Or the JSON metadata on the releases website:

```shell
curl 'https://releases.hashicorp.com/terraform-provider-http/index.json'
```

I'm not aware of a Terraform Provider Registry Protocol or releases endpoint for explicitly showing only the latest version of a provider. A feature request may need to be submitted to the [Terraform CLI repository](https://github.com/hashicorp/terraform/) to see if that can be added. Please note there is also a feature request upstream in the Terraform CLI repository pertaining to adding a command to show outdated providers: https://github.com/hashicorp/terraform/issues/26920. There is also some planned upcoming work to the releases website to enable more metadata and endpoints, however there is no public timeframe or additional details I can share.

If you are using GitHub, the built-in dependency manager [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates) can also be used to automatically propose Terraform version updates.

Hope this helps. 👍

**Comment by darren-johnson** [comment]
Thanks @bflad I'll have a look into those options and raise an issue if needed.
