### ISSUE TITLE
Feature request: Option to ignore failures for data source "http"

### ISSUE THREAD

**Issue by pwillis-els** [hashicorp/terraform-provider-http#107]
### Current Terraform Version
```
$ terraform version
cliv: Executing /home/willis2/.cliv/terraform=1.1.2/bin/terraform
Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.70.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```

### Use-cases
We use the `http` data source to query a list of current IP CIDRs from vendors such as CloudFlare, so we can add those ranges to our security groups. However, occasionally one of those http sources may return a 500 error. We don't need to pull this value on every single terraform apply, because the old values that were already applied will continue to work until the service returns.

### Attempted Solutions
```hcl
# CloudFlare China IPs
data "http" "cloudflare_china_ips" {
  url = "https://api.cloudflare.com/client/v4/ips?china_colo=1"
  request_headers = {
    Accept = "application/json"
  }
}
```
This is an example of our code. I have not found a workaround for this issue because Terraform simply dies with "500 Error".

An alternative to this would be to use a null resources with "local-exec" provisioner to call `curl` or `wget`, but that would not necessarily be portable (Dockerized versions of Terraform might not include `curl`, and behavior would have to change on Windows). Since there is already a data source for doing an HTTP GET. we might as well extend its functionality to support ignoring these failures.

(On earlier versions of Terraform, it actually gives no indication that this module was causing the error (even with TF_DEBUG=TRACE); I had to upgrade Terraform to figure out it was coming from this module block.)

### Proposal
Support an input to the module such as `ignore_errors = true`.

Alternate proposal: support specifying the range of return statuses that signify success (`http_status_success_range = [ 200, 599 ]`).

It also would be great to support passing this as an environment variable so when the error occurs we can temporarily enable/disable this behavior and continue to apply our infrastructure, rather than having to modify the code to ignore errors, which is not necessarily what we want.

**Comment by DonBower** [comment]
We have to be able to not fail on error here, for example if our firewall rules block the site or some other network problem.
I suggest a second output besides `.body`.
Provide another output `.returncode` which will return `200`, `404`, etc.

**Comment by theipster** [comment]
Agreed with the value of returning the HTTP response status code _verbatim_ and without prematurely acting on it - I've dropped a comment in https://github.com/hashicorp/terraform-provider-http/pull/114#issuecomment-1133744243 - WDYT?

That said, what would you expect to happen if a lower-level error occurred (e.g. DNS resolution failure) which effectively resulted in no HTTP status code being available to evaluate at all? It sounds like you'd still prefer to ignore those types of errors too - in which case, we're probably looking at more generic error handling like `try(data.http.foo_request.body, "some fallback body")` instead.
