### ISSUE TITLE
Enable http data source to accept binary data

### ISSUE THREAD

**Issue by nanasi880** [hashicorp/terraform-provider-http#145]
### Terraform CLI and Provider Versions

```
 $ terraform version
Terraform v1.1.8
on darwin_amd64
```

```
provider "registry.terraform.io/hashicorp/http" {
  version = "2.2.0"
}
```

### Use Cases or Problem Statement

HTTP data sources can be used to download externally provided tools and binary data.
For example, to manage a Kubernetes cluster, you can obtain the same version of the kubectl command as the cluster as follows

```
data "http" "kubectl" {
  url = "https://storage.googleapis.com/kubernetes-release/release/v1.24.0/bin/darwin/amd64/kubectl"
}
```

However, current HTTP data sources expect response data to be text data, and dumping response data, for example, as shown below, will produce corrupted data.

```
resource "local_sensitive_file" "kubectl" {
  filename        = "${path.module}/kubectl"
  content_base64  = base64encode(data.http.kubectl.response_body)
  file_permission = "0755"
}
```

### Proposal

Add the `base64_response_body` read-only attribute, which is mainly intended for binary data.
When reading values through this attribute, the provider is not aware of the content, but treats it only as an octet-stream.
The result is encoded in base64 format for safe handling as a string in Terraform.

Example

```
data "http" "kubectl" {
  url = "https://storage.googleapis.com/kubernetes-release/release/v1.24.0/bin/darwin/amd64/kubectl"
}

resource "local_sensitive_file" "kubectl" {
  filename        = "${path.module}/kubectl"
  content_base64  = data.http.kubectl.base64_response_body
  file_permission = "0755"
}
```

### How much impact is this issue causing?

Medium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by merusso** [comment]
The current docs for the http data source [here](https://registry.terraform.io/providers/hashicorp/http/3.4.0/docs/data-sources/http) (v3.4.0) still suggest that binary content is not supported.
> At present this resource can only retrieve data from URLs that respond with text/* or application/json content types, and expects the result to be UTF-8 encoded regardless of the returned content type header.

Does this ticket need to be reopened, or are the docs out-of-date?

**Comment by bendbennett** [comment]
I believe the docs are out of date.

I have opened the following issue and associated PR:

- [Documentation indicates that only text/* or application/json response content types are supported](https://github.com/hashicorp/terraform-provider-http/issues/337#top)
- [Updating documentation](https://github.com/hashicorp/terraform-provider-http/pull/338#top)
