### ISSUE TITLE
Base64 encode response body

### ISSUE THREAD

**Issue by bendbennett** [hashicorp/terraform-provider-http#157]
### Terraform CLI and Provider Versions

terraform v1.2.2
provider v2.2.0

### Use Cases or Problem Statement

Currently, the _http_ provider examines the `Content-Type` header to determine whether the response body is text.
If binary data is contained within the response body, its conversion to `string()` renders the response body unusable and potentially problematic for Terraform to handle. 

### Proposal

Add an attribute which holds a base64 encoded version of the response body.

### How much impact is this issue causing?

Low

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by damlys** [comment]
Looking forward to this improvement :)
