### ISSUE TITLE
Allow PUT requests

### ISSUE THREAD

**Issue by benkeil** [hashicorp/terraform-provider-http#192]
### Terraform CLI and Provider Versions

Terraform v1.2.8
on darwin_arm64

Your version of Terraform is out of date! The latest version
is 1.3.2. You can update by downloading from https://www.terraform.io/downloads.html

### Use Cases or Problem Statement

Can't send PUT requests.

### Proposal

Maybe don't validate the method at all or add PUT

### How much impact is this issue causing?

Low

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sean-freeman** [comment]
Link this GH Issue to fix in PR #298

**Comment by bendbennett** [comment]
@benkeil thank you for opening this issue.

As described in the responses to #298, the _http_ data source, and more broadly, the scope of the _http_ provider is intended to be limited to operations that do not perform any mutation. Consequently, introduction of a resource, which would allow mutation of the target would be outside of this scope. Unfortunately, this means that we are unable to consider your proposal at this time. Perhaps the [restapi](https://registry.terraform.io/providers/Mastercard/restapi) provider might prove to be a suitable alternative, as the `restapi_object` resource allows `POST`, `GET`, `PUT` and `DELETE` operations.
