### ISSUE TITLE
Warning: Missing version constraint for provider "http" in "required_providers" (terraform_required_providers)

### ISSUE THREAD

**Issue by saugat86** [hashicorp/terraform-provider-http#283]
### Terraform CLI and Provider Versions

14 issue(s) found:

Warning: Missing version constraint for provider "http" in "required_providers" (terraform_required_providers)

  on main.tf line 23:
  23: data "http" "iam_source_json_url" {

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_required_providers.md

### Terraform Configuration

```terraform
data "http" "iam_source_json_url" {
  count = local.enabled && var.iam_source_json_url != null ? 1 : 0

  url = var.iam_source_json_url
  request_headers = {
    Accept = "application/json"
  }
}
```
```


### Expected Behavior

No warnings!!

### Actual Behavior

Run without warning.

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

### Logs

_No response_

### Additional Information

Please review these deprecation warnings as soon as possible and merge in the necessary updates.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by austinvalle** [comment]
Hi there @saugat86 👋🏻 ,

This error looks to be coming from TFlint and is unrelated to the actual HTTP provider itself. [It's suggesting](https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_required_providers.md#how-to-fix) that you add a `required_providers` block to your terraform configuration which you can add for `http` to resolve.

If you have an issue with this specific behavior I'd suggest opening a GitHub issue in the `tflint` repository for this ruleset: https://github.com/terraform-linters/tflint-ruleset-terraform/issues
