### ISSUE TITLE
Unable to get proper response from Auth0 get token call

### ISSUE THREAD

**Issue by tommy38hk** [hashicorp/terraform-provider-http#304]
### Terraform CLI and Provider Versions

Terraform v1.4.6

### Terraform Configuration

```terraform
data "http" "auth0_token" {
  url = var.auth0_token_endpoint
  request_body = local.auth0_json
  method = "POST"
  request_headers = {
    Accept = "application/json"
  }
}
locals {
  auth0_json=jsonencode({
    client_id     = var.auth0_client_client_id
    client_secret = var.auth0_client_client_secret
    audience      = var.edms_registration_service_api_identifier
    grant_type    = "client_credentials"
  })
}
output "auth0_json_response" {
  value = data.http.auth0_token.response_body
}
output "auth0_json_request" {
  value = local.auth0_json
}
```

### Expected Behavior

Be able to return the auth0 token

### Actual Behavior

auth0_json_response = "{\"error\":\"access_denied\",\"error_description\":\"Unauthorized\"}"

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

Medium

### Additional Information

Proper token can be obtained using CURL command for the same credentials 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by austinvalle** [comment]
Hi there @tommy38hk, thanks for filing the issue and sorry you're running into trouble here.

Are you able to share the CURL command structure you're using that is successfully making the API call? The example configuration you provided looks like it's encoding the HTTP request body as `application/json`, whereas the Auth0 documentation for [POST /oauth/token](https://auth0.com/docs/api/authentication#client-credentials-flow) is expecting `application/x-www-form-urlencoded` in the request body.

**Comment by tommy38hk** [comment]
Hi @austinvalle 
Here's the CURL command from Auth0, I have replaced the actual values of the sensitive fields.

curl --request POST \
  --url https://my.auth0.com/oauth/token \
  --header 'content-type: application/json' \
  --data '{"client_id":"my-auth0-client-id","client_secret":"my-ayth0-client-secret","audience":"my-auth0-api-audience","grant_type":"client_credentials"}'

**Comment by austinvalle** [comment]
Quick test before I try and reproduce that issue, can you try updating your data block to use the `Content-Type` header, currently it only has `Accept` set:

```terraform
data "http" "auth0_token" {
  url = var.auth0_token_endpoint
  request_body = local.auth0_json
  method = "POST"
  request_headers = {
    content-type = "application/json"
    accept = "application/json"
  }
}
```

**Comment by tommy38hk** [comment]
Yes, that fixed the issue. Thank you so much
