### ISSUE TITLE
Add support for rate limiting

### ISSUE THREAD

**Issue by tobiasbp** [hashicorp/terraform-provider-http#334]
### Terraform CLI and Provider Versions

Terraform: 1.6.1
Provider: 3.4.0

### Use Cases or Problem Statement

To many requests to an API within a window of time, results in new requests being rejected.

### Proposal

Add a _'rate_limit'_ setting which holds a _number_ representing the number of requests per second the provider is allowed to perform.

### How much impact is this issue causing?

High

### Additional Information

The use case here is to get lots of organizations and users from an API and deploying those users and groups on another system using a dedicated Terraform provider for that platform. This is currently not possible because requests to the API holding the orgs and users are rejected after a certain number of requests have been made. If the rate of the requests could be controlled, it should be possible to find a rate at which the rejection issue would not occur.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tobiasbp** [comment]
Would a PR for this be welcomed?

**Comment by bendbennett** [comment]
Hi @tobiasbp 👋 

Thank you for opening this issue. Prior to opening a PR, it might be worth seeing how many up-votes that this issue receives so that we have an indication of the level of community interest.

**Comment by bflad** [comment]
One thing to potentially consider when evaluating this feature request is whether this form of complexity is warranted in this generic HTTP request provider. Rate limiting tends to have varied solutions across APIs, whether it be header-based or undetectable. APIs with rate limiting requirements should likely have those sorts of behaviors encoded in their own provider, so practitioners needing to interface with the API do not need to implement specific configuration.

**Comment by tobiasbp** [comment]
I think the problem I am trying to solve by adding rate limiting, will be solved if the connection making the HTTP requests could be reused. There is an issue for [that here](https://github.com/hashicorp/terraform-provider-http/issues/335). I'll close this feature request.
