### ISSUE TITLE
Detailed messaging on http error responses

### ISSUE THREAD

**Issue by michaelPotter** [hashicorp/terraform-provider-http#70]
We are using the http provider in several places in our code. When one of our http resources returns an error response like 401 or 404 it can be hard to determine which one failed since the error message doesn't include details about the request.

### Terraform Version
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/http v2.1.0

### Affected Resource(s)
http_http datasource

### Terraform Configuration Files
```hcl
# One of these calls fails with a 404... but which one?
data "http" "foobar" {
  url = "https://google.com/foobar"
}

data "http" "helloworld" {
  url = "https://google.com/helloworld"
}
```

### Expected Behavior
It would be nice if the error message indicated which request failed. For example:
> Error: HTTP request error from [https://google.com/thispagedoesntexist]. Response code: 404

### Actual Behavior
The displayed error is:
> Error: HTTP request error. Response code: 404

**Comment by bflad** [comment]
Hi @michaelPotter 👋  Thank you for raising this and sorry you ran into trouble here.

This issue is resolved in more recent versions of Terraform CLI by showing the configuration context:

```terraform
terraform {
  required_version = "0.14.11"
  required_providers {
    http = {
      source  = "hashicorp/http"
      version = "2.1.0"
    }
  }
}

data "http" "foobar" {
  url = "https://google.com/foobar"
}

data "http" "helloworld" {
  url = "https://google.com/helloworld"
}
```

```console
$ terraform0.14.11 apply

Error: HTTP request error. Response code: 404

  on main.tf line 15, in data "http" "helloworld":
  15: data "http" "helloworld" {

```

The error message can likely be updated as well to include the URL for clarity, so I am going to keep this open for now until that can be discussed further.

**Comment by bflad** [comment]
As mentioned above, the configuration context should be present when an error is returned. Also with the current version of the provider (v3.4.1), the URL should also be present in the error messaging. If you are still experiencing unclear error messaging, please open a new issue. Thanks!
