### ISSUE TITLE
Create provider design doc 

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-provider-http#89]
Maintenance of the standard library providers prioritises stability and correctness relative to the provider's intended feature set. Create a design document describing this feature set, and any other design considerations which influence the architecture of the provider and what can and cannot be added to it.

To include:

Document the design considerations and decisions around including other HTTP verbs in this provider.

Some context: https://github.com/hashicorp/terraform-provider-http/pull/20#issuecomment-507936261

https://github.com/hashicorp/terraform-provider-http/pull/85

**Comment by bendbennett** [comment]
Closed by #135
